/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c6c6c6",
        "on-secondary-container": "#00714d",
        "primary-fixed": "#e2e2e2",
        "outline-variant": "var(--lc-outline-variant)",
        "on-primary-fixed-variant": "#474747",
        surface: "var(--lc-surface)",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed-variant": "#005236",
        error: "#ba1a1a",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-container": "#848484",
        "tertiary-container": "#2a1700",
        "surface-variant": "var(--lc-surface-variant)",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#b87500",
        "surface-container-lowest": "var(--lc-surface-container-lowest)",
        "on-secondary-fixed": "#002113",
        "surface-container-high": "var(--lc-surface-container-high)",
        "primary-container": "#1b1b1b",
        "surface-container": "var(--lc-surface-container)",
        "on-surface-variant": "var(--lc-on-surface-variant)",
        "tertiary-fixed": "#ffddb8",
        secondary: "#006c49",
        primary: "var(--lc-primary)",
        "on-surface": "var(--lc-on-surface)",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary": "var(--lc-on-primary)",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-highest": "var(--lc-surface-container-highest)",
        "on-error-container": "#93000a",
        "surface-container-low": "var(--lc-surface-container-low)",
        "secondary-fixed": "#6ffbbe",
        "on-background": "var(--lc-on-surface)",
        "secondary-fixed-dim": "#4edea3",
        background: "var(--lc-background)",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "on-tertiary-fixed": "#2a1700",
        outline: "var(--lc-outline)",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#ffb95f",
        "error-container": "#ffdad6",
        "inverse-surface": "#303030",
        "code-keyword": "var(--lc-code-keyword)",
        "code-comment": "var(--lc-code-comment)",
        "code-fg": "var(--lc-code-fg)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        xl: "32px",
        margin: "32px",
        sm: "8px",
        xs: "4px",
        xxl: "48px",
        unit: "8px",
        md: "16px",
      },
      fontFamily: {
        "code-block": ["JetBrains Mono", "monospace"],
        "ui-label": ["JetBrains Mono", "monospace"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-block": [
          "14px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "ui-label": [
          "14px",
          {
            lineHeight: "1",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.6s ease-out both",
        "fade-up-delay": "fade-up 0.6s ease-out 0.15s both",
        "fade-up-delay-2": "fade-up 0.6s ease-out 0.3s both",
      },
    },
  },
  important: "html",
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: ["forest"],
  },
};
